name: lando-bedrock-nextjs
recipe: wordpress
proxy:
  pma:
    - pma.lando-bedrock-nextjs.lndo.site
  frontend:
    - frontend.lando-bedrock-nextjs.lndo.site:3000
env_file:
  - .env
config:
  webroot: backend/web
services:
  appserver:
    type: php:8.2
  frontend:
    type: node:18
    command: cd /app/frontend && yarn dev
    build:
      - cd /app/frontend && yarn
    ssl: true
  pma:
    type: phpmyadmin
    hosts: database
  database:
    type: mariadb
    portforward: true
tooling:
  generate-env:
    service: appserver
    dir: /app
    cmd:
      - wp package install aaemnnosttv/wp-cli-dotenv-command:^2.0
      - wp dotenv init --template=.env.example --with-salts
  yarn:
    service: frontend
    dir: /app/frontend
