name: lando-bedrock
recipe: wordpress
proxy:
  pma:
    - pma.lando-bedrock.lndo.site
env_file:
  - .env
config:
  webroot: backend/web
services:
  appserver:
    type: php:8.2
  pma:
    type: phpmyadmin
    hosts: database
  database:
    type: mariadb
    portforward: true
tooling:
  generate-env:
    service: appserver
    dir: /app
    cmd:
      - wp package install aaemnnosttv/wp-cli-dotenv-command:^2.0
      - wp dotenv init --template=.env.example --with-salts