import "../../faust.config";
import React from "react";
import { useRouter } from "next/router";
import { WordPressBlocksProvider, fromThemeJson } from '@faustwp/blocks';
import { FaustProvider } from "@faustwp/core";
import blocks from '../wp-blocks';
import "../styles/globals.css";
// import '../styles/blocks.scss'; // <-- Import block styles from WordPress.
import '../../globalStylesheet.css'; // <-- Generated by @faustwp/cli
import themeJson from '../styles/theme.json';

import { AppProps } from "next/app";

export default function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();

  return (
    <FaustProvider pageProps={pageProps}>
      <WordPressBlocksProvider
        config={{
          blocks,
          theme: fromThemeJson(themeJson),
        }}>
        <Component {...pageProps} key={router.asPath} />
      </WordPressBlocksProvider>
    </FaustProvider>
  );
}
